name: Fly Deploy

on: push

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Validate Go modules
        run: |
          go mod tidy -v
          go mod verify

      - run: go build -a -v

  deploy:
    needs: build
      name: Deploy app
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}